// Action Type을 상수로 정의
export const GET_SCHEDULES = 'GET_SCHEDULES';
export const ADD_SCHEDULES = 'ADD_SCHEDULES';
export const EDIT_SCHEDULES = 'EDIT_SCHEDULES';
export const REMOVE_SCHEDULES = 'REMOVE_SCHEDULES';
export const SELECT_DATE = 'SELECT_DATE';
export const FILTERED_SCHEDULES = 'FILTERED_SCHEDULES';
export const SET_LOADING = 'SET_LOADING';
