// Action Type을 상수로 정의
export const GET_SCHEDULES = 'GET_SCHEDULES';
export const ADD_SCHEDULES = 'ADD_SCHEDULES';
export const EDIT_SCHEDULES = 'EDIT_SCHEDULES';
export const REMOVE_SCHEDULES = 'REMOVE_SCHEDULES';
export const SELECT_DATE = 'SELECT_DATE';
export const FILTERED_SCHEDULES = 'FILTERED_SCHEDULES';
export const SET_SELECTED_SCHEDULE = 'SET_SELECTED_SCHEDULE';
export const CLEAR_SCHEDULES = 'CLEAR_SCHEDULES';
export const SET_FILTER_CATEGORY = 'SET_FILTER_CATEGORY';

export const ADMIN_GET_EMPLOYEE = 'ADMIN_GET_EMPLOYEE';
export const ADMIN_USER_SEARCH_ID = 'ADMIN_USER_SEARCH_ID';

export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

export const SET_LOADING = 'SET_LOADING'; // suspanse로 바꿔야 함

export const SET_MODAL_OPEN = 'SET_MODAL_OPEN';
export const SET_CONFIRM_MODAL_OPEN = 'SET_CONFIRM_MODAL_OPEN';
export const SET_SCHEDULE_ADD_MODAL_OPEN = 'SET_SCHEDULE_ADD_MODAL_OPEN';
export const SET_SCHEDULE_EDIT_MODAL_OPEN = 'SET_SCHEDULE_EDIT_MODAL_OPEN';
export const SET_SCHEDULE_DELETE_MODAL_OPEN = 'SET_SCHEDULE_DELETE_MODAL_OPEN';
